### ISSUE TITLE
Unable to publish the repo in SharePoint

### ISSUE THREAD

**Issue by jairamjidgekar** [obrassard/action-sharepoint-publish#20]
Hi, 

I am trying to clone my repo in the SharePoint. 

When I run the actions .yml file, I get the below error:

Can you please let me know what might be the issue?

I have added the client Id and Secret key along with the URL and Library folder. 
```
[06:39:09] spsave: Error occured:
[06:39:09] spsave: Error: read ECONNRESET

[06:39:09] spsave: Stack trace:

[06:39:09] spsave: RequestError: Error: read ECONNRESET
    at new RequestError (/app/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:[46](https://github.com/jairamjidgekar/KDB/actions/runs/4955972182/jobs/8865889443#step:4:47):31)
    at self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/app/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:375:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at coreRequest (/app/node_modules/sp-request/lib/src/core/SPRequest.js:22:16)
    at spRequestFunc (/app/node_modules/sp-request/lib/src/core/SPRequest.js:69:20)
    at Function.spRequestFunc.(anonymous function) [as post] (/app/node_modules/sp-request/lib/src/core/SPRequest.js:109:24)
    at /app/node_modules/sp-request/lib/src/core/SPRequest.js:87:27
From previous event:
    at Function.spRequestFunc.requestDigest (/app/node_modules/sp-request/lib/src/core/SPRequest.js:79:16)
    at /app/node_modules/spsave/lib/src/core/FileSaver.js:54:36
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:6[49](https://github.com/jairamjidgekar/KDB/actions/runs/4955972182/jobs/8865889443#step:4:50):5)
From previous event:
    at FileSaver.saveFile (/app/node_modules/spsave/lib/src/core/FileSaver.js:53:14)
    at FileSaver.save (/app/node_modules/spsave/lib/src/core/FileSaver.js:38:18)
    at saveSingleFile (/app/node_modules/spsave/lib/src/core/SPSave.js:80:76)
    at /app/node_modules/spsave/lib/src/core/SPSave.js:41:13
From previous event:
    at spsave (/app/node_modules/spsave/lib/src/core/SPSave.js:13:12)
    at Object.<anonymous> (/app/index.js:28:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:[52](https://github.com/jairamjidgekar/KDB/actions/runs/4955972182/jobs/8865889443#step:4:53)8:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:[57](https://github.com/jairamjidgekar/KDB/actions/runs/4955972182/jobs/8865889443#step:4:58)6:3)
```

**Comment by obrassard** [comment]
Hello @jairamjidgekar,

This error is very generic, and unfortunately there is not enough information in the stack trace for me to conclude the cause of the issue. All I can say is that it seems to be a network error thrown by the [spsave package](https://github.com/s-KaiNet/spsave). Is there more informations in the error log (above or below) ? 

If you are sure your credentials are correct, and there is no other usefull informations in the console, you could try opening an issue with spsave here : https://github.com/s-KaiNet/spsave/issues they might have more insights on the issue.
